---
- name: Find *.sqlite files
  vars:
    sqlite_paths:
      server1070:
        - "/home/seclab/unm2h/git/nn/graphganfeddrugbankFinetuneOndrugbank2/molecularGAN/GraphGANFed/BalancedGANFed_SECNetUNM"
      # 1080 (as seen from 1660)
      server1080:
        - "/home/secnet/git/BalancedGANFed_SECNetUNM"
      m4mini:
        - "/Users/watney/git/BalancedGANFed_SECNetUNM"
      # 1660 itself (local paths)
      localhost:
        - "/home/secnet/git/BalancedGANFed_SECNetUNM"
      # Add other servers as needed
  hosts: all
  tasks:
  - name: Find *.sqlite files
    find:
      paths: "{{ sqlite_paths[inventory_hostname] }}"
      patterns: "*.sqlite"
      # ignore: true
      # ignore_patterns:
      #   - "progressDict.*.sqlite"
    register: sqlite_files

  - name: Find progressDict.*.sqlite files specifically
    find:
      paths: "{{ sqlite_paths[inventory_hostname] }}"
      patterns: "progressDict.*.sqlite"
    register: progress_dict_files
    tags: progress_dict

  - name: Display found progress_dict_files
    debug:
      var: progress_dict_files
    tags: progress_dict

  - name: Perform git pull on repository directories
    git:
      repo: "https://github.com/SECNetLabUNM/BalancedGANFed_SECNetUNM.git"
      dest: "{{ item }}"
      update: yes
    loop: "{{ sqlite_paths[inventory_hostname] }}"
    when: sqlite_paths[inventory_hostname] is defined
    tags: git_pull

  - name: Update git remote URL
    shell: git remote set-url origin https://github.com/SECNetLabUNM/BalancedGANFed_SECNetUNM.git
    args:
      chdir: "{{ item }}"
    loop: "{{ sqlite_paths[inventory_hostname] }}"
    when: sqlite_paths[inventory_hostname] is defined
    tags: fix_git_remote
