---
- name: Find *.sqlite files
  vars:
    sqlite_paths:
      # 1080
      server1080:
        - "/home/secnet/git/BalancedGANFed_SECNetUNM"
      # 1660
      localhost:
        - "/home/secnet/git/BalancedGANFed_SECNetUNM"
      localhost:
        - "/home/seclab/unm2h/git/nn/graphganfeddrugbankFinetuneOndrugbank2/molecularGAN/GraphGANFed/BalancedGANFed_SECNetUNM"
  hosts: all
  tasks:
  - name: Find *.sqlite files
    find:
      paths: "{{ sqlite_paths[inventory_hostname] }}"
      patterns: "*.sqlite"
      # ignore: true
      # ignore_patterns:
      #   - "progressDict.*.sqlite"
    register: sqlite_files

  - name: Display found files
    debug:
      var: sqlite_files
